/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT MODIFY */

/*
 * schema-defined QAPI visitor functions
 *
 * Copyright IBM, Corp. 2011
 *
 * Authors:
 *  Anthony Liguori   <aliguori@us.ibm.com>
 *
 * This work is licensed under the terms of the GNU LGPL, version 2.1 or later.
 * See the COPYING.LIB file in the top-level directory.
 *
 */

#include "qga-qapi-visit.h"

void visit_type_GuestAgentCommandInfo(Visitor *m, GuestAgentCommandInfo ** obj, const char *name, Error **errp)
{
    if (error_is_set(errp)) {
        return;
    }
    visit_start_struct(m, (void **)obj, "GuestAgentCommandInfo", name, sizeof(GuestAgentCommandInfo), errp);
    if (obj && !*obj) {
        goto end;
    }
    visit_type_str(m, (obj && *obj) ? &(*obj)->name : NULL, "name", errp);
    visit_type_bool(m, (obj && *obj) ? &(*obj)->enabled : NULL, "enabled", errp);
end:
    visit_end_struct(m, errp);
}

void visit_type_GuestAgentCommandInfoList(Visitor *m, GuestAgentCommandInfoList ** obj, const char *name, Error **errp)
{
    GenericList *i, **prev = (GenericList **)obj;

    if (error_is_set(errp)) {
        return;
    }
    visit_start_list(m, name, errp);

    for (; (i = visit_next_list(m, prev, errp)) != NULL; prev = &i) {
        GuestAgentCommandInfoList *native_i = (GuestAgentCommandInfoList *)i;
        visit_type_GuestAgentCommandInfo(m, &native_i->value, NULL, errp);
    }

    visit_end_list(m, errp);
}

void visit_type_GuestAgentInfo(Visitor *m, GuestAgentInfo ** obj, const char *name, Error **errp)
{
    if (error_is_set(errp)) {
        return;
    }
    visit_start_struct(m, (void **)obj, "GuestAgentInfo", name, sizeof(GuestAgentInfo), errp);
    if (obj && !*obj) {
        goto end;
    }
    visit_type_str(m, (obj && *obj) ? &(*obj)->version : NULL, "version", errp);
    visit_type_GuestAgentCommandInfoList(m, (obj && *obj) ? &(*obj)->supported_commands : NULL, "supported_commands", errp);
end:
    visit_end_struct(m, errp);
}

void visit_type_GuestAgentInfoList(Visitor *m, GuestAgentInfoList ** obj, const char *name, Error **errp)
{
    GenericList *i, **prev = (GenericList **)obj;

    if (error_is_set(errp)) {
        return;
    }
    visit_start_list(m, name, errp);

    for (; (i = visit_next_list(m, prev, errp)) != NULL; prev = &i) {
        GuestAgentInfoList *native_i = (GuestAgentInfoList *)i;
        visit_type_GuestAgentInfo(m, &native_i->value, NULL, errp);
    }

    visit_end_list(m, errp);
}

void visit_type_GuestFileRead(Visitor *m, GuestFileRead ** obj, const char *name, Error **errp)
{
    if (error_is_set(errp)) {
        return;
    }
    visit_start_struct(m, (void **)obj, "GuestFileRead", name, sizeof(GuestFileRead), errp);
    if (obj && !*obj) {
        goto end;
    }
    visit_type_int(m, (obj && *obj) ? &(*obj)->count : NULL, "count", errp);
    visit_type_str(m, (obj && *obj) ? &(*obj)->buf_b64 : NULL, "buf-b64", errp);
    visit_type_bool(m, (obj && *obj) ? &(*obj)->eof : NULL, "eof", errp);
end:
    visit_end_struct(m, errp);
}

void visit_type_GuestFileReadList(Visitor *m, GuestFileReadList ** obj, const char *name, Error **errp)
{
    GenericList *i, **prev = (GenericList **)obj;

    if (error_is_set(errp)) {
        return;
    }
    visit_start_list(m, name, errp);

    for (; (i = visit_next_list(m, prev, errp)) != NULL; prev = &i) {
        GuestFileReadList *native_i = (GuestFileReadList *)i;
        visit_type_GuestFileRead(m, &native_i->value, NULL, errp);
    }

    visit_end_list(m, errp);
}

void visit_type_GuestFileWrite(Visitor *m, GuestFileWrite ** obj, const char *name, Error **errp)
{
    if (error_is_set(errp)) {
        return;
    }
    visit_start_struct(m, (void **)obj, "GuestFileWrite", name, sizeof(GuestFileWrite), errp);
    if (obj && !*obj) {
        goto end;
    }
    visit_type_int(m, (obj && *obj) ? &(*obj)->count : NULL, "count", errp);
    visit_type_bool(m, (obj && *obj) ? &(*obj)->eof : NULL, "eof", errp);
end:
    visit_end_struct(m, errp);
}

void visit_type_GuestFileWriteList(Visitor *m, GuestFileWriteList ** obj, const char *name, Error **errp)
{
    GenericList *i, **prev = (GenericList **)obj;

    if (error_is_set(errp)) {
        return;
    }
    visit_start_list(m, name, errp);

    for (; (i = visit_next_list(m, prev, errp)) != NULL; prev = &i) {
        GuestFileWriteList *native_i = (GuestFileWriteList *)i;
        visit_type_GuestFileWrite(m, &native_i->value, NULL, errp);
    }

    visit_end_list(m, errp);
}

void visit_type_GuestFileSeek(Visitor *m, GuestFileSeek ** obj, const char *name, Error **errp)
{
    if (error_is_set(errp)) {
        return;
    }
    visit_start_struct(m, (void **)obj, "GuestFileSeek", name, sizeof(GuestFileSeek), errp);
    if (obj && !*obj) {
        goto end;
    }
    visit_type_int(m, (obj && *obj) ? &(*obj)->position : NULL, "position", errp);
    visit_type_bool(m, (obj && *obj) ? &(*obj)->eof : NULL, "eof", errp);
end:
    visit_end_struct(m, errp);
}

void visit_type_GuestFileSeekList(Visitor *m, GuestFileSeekList ** obj, const char *name, Error **errp)
{
    GenericList *i, **prev = (GenericList **)obj;

    if (error_is_set(errp)) {
        return;
    }
    visit_start_list(m, name, errp);

    for (; (i = visit_next_list(m, prev, errp)) != NULL; prev = &i) {
        GuestFileSeekList *native_i = (GuestFileSeekList *)i;
        visit_type_GuestFileSeek(m, &native_i->value, NULL, errp);
    }

    visit_end_list(m, errp);
}

void visit_type_GuestFsfreezeStatus(Visitor *m, GuestFsfreezeStatus * obj, const char *name, Error **errp)
{
    visit_type_enum(m, (int *)obj, GuestFsfreezeStatus_lookup, "GuestFsfreezeStatus", name, errp);
}

void visit_type_GuestIpAddressType(Visitor *m, GuestIpAddressType * obj, const char *name, Error **errp)
{
    visit_type_enum(m, (int *)obj, GuestIpAddressType_lookup, "GuestIpAddressType", name, errp);
}

void visit_type_GuestIpAddress(Visitor *m, GuestIpAddress ** obj, const char *name, Error **errp)
{
    if (error_is_set(errp)) {
        return;
    }
    visit_start_struct(m, (void **)obj, "GuestIpAddress", name, sizeof(GuestIpAddress), errp);
    if (obj && !*obj) {
        goto end;
    }
    visit_type_str(m, (obj && *obj) ? &(*obj)->ip_address : NULL, "ip-address", errp);
    visit_type_GuestIpAddressType(m, (obj && *obj) ? &(*obj)->ip_address_type : NULL, "ip-address-type", errp);
    visit_type_int(m, (obj && *obj) ? &(*obj)->prefix : NULL, "prefix", errp);
end:
    visit_end_struct(m, errp);
}

void visit_type_GuestIpAddressList(Visitor *m, GuestIpAddressList ** obj, const char *name, Error **errp)
{
    GenericList *i, **prev = (GenericList **)obj;

    if (error_is_set(errp)) {
        return;
    }
    visit_start_list(m, name, errp);

    for (; (i = visit_next_list(m, prev, errp)) != NULL; prev = &i) {
        GuestIpAddressList *native_i = (GuestIpAddressList *)i;
        visit_type_GuestIpAddress(m, &native_i->value, NULL, errp);
    }

    visit_end_list(m, errp);
}

void visit_type_GuestNetworkInterface(Visitor *m, GuestNetworkInterface ** obj, const char *name, Error **errp)
{
    if (error_is_set(errp)) {
        return;
    }
    visit_start_struct(m, (void **)obj, "GuestNetworkInterface", name, sizeof(GuestNetworkInterface), errp);
    if (obj && !*obj) {
        goto end;
    }
    visit_type_str(m, (obj && *obj) ? &(*obj)->name : NULL, "name", errp);
    visit_start_optional(m, (obj && *obj) ? &(*obj)->has_hardware_address : NULL, "hardware-address", errp);
    if ((*obj)->has_hardware_address) {
        visit_type_str(m, (obj && *obj) ? &(*obj)->hardware_address : NULL, "hardware-address", errp);
    }
    visit_end_optional(m, errp);
    visit_start_optional(m, (obj && *obj) ? &(*obj)->has_ip_addresses : NULL, "ip-addresses", errp);
    if ((*obj)->has_ip_addresses) {
        visit_type_GuestIpAddressList(m, (obj && *obj) ? &(*obj)->ip_addresses : NULL, "ip-addresses", errp);
    }
    visit_end_optional(m, errp);
end:
    visit_end_struct(m, errp);
}

void visit_type_GuestNetworkInterfaceList(Visitor *m, GuestNetworkInterfaceList ** obj, const char *name, Error **errp)
{
    GenericList *i, **prev = (GenericList **)obj;

    if (error_is_set(errp)) {
        return;
    }
    visit_start_list(m, name, errp);

    for (; (i = visit_next_list(m, prev, errp)) != NULL; prev = &i) {
        GuestNetworkInterfaceList *native_i = (GuestNetworkInterfaceList *)i;
        visit_type_GuestNetworkInterface(m, &native_i->value, NULL, errp);
    }

    visit_end_list(m, errp);
}
