#!/bin/bash

TMP="/tmp/project"
PROJECT_HOME="/lab"
PROJECT_ARCHIVE="awesomesauce2.zip"

# If no command line parameters given, provide usage banner
if [ $# -eq 0 ]
  then
    cat <<-____HERE    
Usage: setup
   setup  Extract project to $PROJECT_HOME
   ...    Future utility options TBD

____HERE
    exit
fi

# Parameter check
if [ "$1" != "setup" ]; then
  echo "Unrecognized parameter. Run with no parameters for help."
  exit
fi

# Clear temporary directory just to be sure
rm -rf "$TMP"

# Check if expansion target directory has anything in it
if [ "$(ls -A $PROJECT_HOME)" ]; then
  # Confirm deletion of contents of project folder
  read -p "> $PROJECT_HOME is not empty (includes hidden files). Delete contents before extracting project [y/n]? " -n 1 -r
  if [[ $REPLY =~ ^[Yy]$ ]]
  then
    echo "> Clearing $PROJECT_HOME ..."
    rm -rf "$PROJECT_HOME"/*
  else
    echo "> Project extraction cancelled."
    exit
  fi
fi

# Extract archive listing and regex to determine base directory of files
BASEDIR=`unzip -l /home/drsurly/$PROJECT_ARCHIVE | grep -E -o 'mvandervoord[^/]+' | head -1`

# Extract the archive
echo "> Extracting project..."
unzip -q "/home/drsurly/$PROJECT_ARCHIVE" -d $TMP

# Delete any git junk -- first files and then directories
find $TMP -type f -iname ".git*" -delete
find $TMP -type d -name ".git" -exec rm -rf "{}" \;

# Move extracted contents below $basedir to new base directory of /lab
mv "$TMP/$BASEDIR"/* "$PROJECT_HOME"

chmod +x "$PROJECT_HOME"/start_lab

# Clean up temporary directory
rm -rf "$TMP"

echo "> Done."
echo "> See project contents in $PROJECT_HOME"
