#!/bin/bash

# Download project as zip file
echo "Downloading project"
curl -fsSL "https://bitbucket.org/mvandervoord/awesomesauce/get/HEAD.zip" -o /tmp/project.zip

# Extract archive listing and regex to determine base directory of files
basedir=`unzip -l /tmp/project.zip | grep -E -o 'mvandervoord[^/]+' | head -1`

# Extract the archive
echo "Extracting project"
unzip -q /tmp/project.zip -d /tmp

# Delete any git junk -- first files and then directories
find /tmp -type f -iname ".git*" -delete
find /tmp -type d -name ".git" -exec rm -rf "{}" \;

# Move extracted contents below $basedir to new base directory of /lab
mv /tmp/$basedir/* /lab

# Clean up /tmp
rm -rf /tmp/*

echo "Done"
